/*
 Navicat Premium Data Transfer

 Source Server         : awm2023
 Source Server Type    : PostgreSQL
 Source Server Version : 130003
 Source Host           : localhost:25432
 Source Catalog        : gis
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 130003
 File Encoding         : 65001

 Date: 04/11/2022 13:49:44
*/


-- ----------------------------
-- Table structure for auth_user
-- ----------------------------
DROP TABLE IF EXISTS "public"."auth_user";
CREATE TABLE "public"."auth_user" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "password" varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
  "last_login" timestamptz(6),
  "is_superuser" bool NOT NULL,
  "username" varchar(150) COLLATE "pg_catalog"."default" NOT NULL,
  "first_name" varchar(150) COLLATE "pg_catalog"."default" NOT NULL,
  "last_name" varchar(150) COLLATE "pg_catalog"."default" NOT NULL,
  "email" varchar(254) COLLATE "pg_catalog"."default" NOT NULL,
  "is_staff" bool NOT NULL,
  "is_active" bool NOT NULL,
  "date_joined" timestamptz(6) NOT NULL
)
;

-- ----------------------------
-- Records of auth_user
-- ----------------------------
INSERT INTO "public"."auth_user" VALUES (1, 'pbkdf2_sha256$390000$8buwP88AeGkwhOZi7xbSvU$qg2lz93kvfir9WUAuaBZtH8rn39C318vCECoyF5BOnI=', '2022-11-03 12:21:42.326535+00', 't', 'yushun', '', '', 'd18130495@mytudublin.ie', 't', 't', '2022-10-18 13:52:31.547603+00');
INSERT INTO "public"."auth_user" VALUES (2, 'pbkdf2_sha256$390000$wY7ukr7Ax3m3oxqFgD8jYy$pDEEvArD22Q4YPVDjHN7EgaL5w3+xoC9AxVrp6n9ieI=', '2022-11-04 13:38:50.696882+00', 'f', 'Alex', '', '', '', 'f', 't', '2022-11-02 23:17:28.615988+00');

-- ----------------------------
-- Auto increment value for auth_user
-- ----------------------------
SELECT setval('"public"."auth_user_id_seq"', 2, true);

-- ----------------------------
-- Indexes structure for table auth_user
-- ----------------------------
CREATE INDEX "auth_user_username_6821ab7c_like" ON "public"."auth_user" USING btree (
  "username" COLLATE "pg_catalog"."default" "pg_catalog"."varchar_pattern_ops" ASC NULLS LAST
);

-- ----------------------------
-- Uniques structure for table auth_user
-- ----------------------------
ALTER TABLE "public"."auth_user" ADD CONSTRAINT "auth_user_username_key" UNIQUE ("username");

-- ----------------------------
-- Primary Key structure for table auth_user
-- ----------------------------
ALTER TABLE "public"."auth_user" ADD CONSTRAINT "auth_user_pkey" PRIMARY KEY ("id");
