/*
 Navicat Premium Data Transfer

 Source Server         : awm2023
 Source Server Type    : PostgreSQL
 Source Server Version : 130003
 Source Host           : localhost:25432
 Source Catalog        : gis
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 130003
 File Encoding         : 65001

 Date: 04/11/2022 13:50:17
*/


-- ----------------------------
-- Table structure for django_migrations
-- ----------------------------
DROP TABLE IF EXISTS "public"."django_migrations";
CREATE TABLE "public"."django_migrations" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "app" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "name" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "applied" timestamptz(6) NOT NULL
)
;

-- ----------------------------
-- Records of django_migrations
-- ----------------------------
INSERT INTO "public"."django_migrations" VALUES (1, 'contenttypes', '0001_initial', '2022-10-18 13:51:27.834758+00');
INSERT INTO "public"."django_migrations" VALUES (2, 'auth', '0001_initial', '2022-10-18 13:51:27.997963+00');
INSERT INTO "public"."django_migrations" VALUES (3, 'admin', '0001_initial', '2022-10-18 13:51:28.035935+00');
INSERT INTO "public"."django_migrations" VALUES (4, 'admin', '0002_logentry_remove_auto_add', '2022-10-18 13:51:28.044437+00');
INSERT INTO "public"."django_migrations" VALUES (5, 'admin', '0003_logentry_add_action_flag_choices', '2022-10-18 13:51:28.053051+00');
INSERT INTO "public"."django_migrations" VALUES (6, 'contenttypes', '0002_remove_content_type_name', '2022-10-18 13:51:28.07046+00');
INSERT INTO "public"."django_migrations" VALUES (7, 'auth', '0002_alter_permission_name_max_length', '2022-10-18 13:51:28.079959+00');
INSERT INTO "public"."django_migrations" VALUES (8, 'auth', '0003_alter_user_email_max_length', '2022-10-18 13:51:28.08946+00');
INSERT INTO "public"."django_migrations" VALUES (9, 'auth', '0004_alter_user_username_opts', '2022-10-18 13:51:28.098078+00');
INSERT INTO "public"."django_migrations" VALUES (10, 'auth', '0005_alter_user_last_login_null', '2022-10-18 13:51:28.107578+00');
INSERT INTO "public"."django_migrations" VALUES (11, 'auth', '0006_require_contenttypes_0002', '2022-10-18 13:51:28.112755+00');
INSERT INTO "public"."django_migrations" VALUES (12, 'auth', '0007_alter_validators_add_error_messages', '2022-10-18 13:51:28.121737+00');
INSERT INTO "public"."django_migrations" VALUES (13, 'auth', '0008_alter_user_username_max_length', '2022-10-18 13:51:28.137951+00');
INSERT INTO "public"."django_migrations" VALUES (14, 'auth', '0009_alter_user_last_name_max_length', '2022-10-18 13:51:28.147951+00');
INSERT INTO "public"."django_migrations" VALUES (15, 'auth', '0010_alter_group_name_max_length', '2022-10-18 13:51:28.15796+00');
INSERT INTO "public"."django_migrations" VALUES (16, 'auth', '0011_update_proxy_permissions', '2022-10-18 13:51:28.167961+00');
INSERT INTO "public"."django_migrations" VALUES (17, 'auth', '0012_alter_user_first_name_max_length', '2022-10-18 13:51:28.176962+00');
INSERT INTO "public"."django_migrations" VALUES (18, 'awm2023', '0001_initial', '2022-10-18 13:51:28.234512+00');
INSERT INTO "public"."django_migrations" VALUES (19, 'awm2023', '0002_profile', '2022-10-18 13:51:28.270141+00');
INSERT INTO "public"."django_migrations" VALUES (20, 'sessions', '0001_initial', '2022-10-18 13:51:28.303558+00');

-- ----------------------------
-- Auto increment value for django_migrations
-- ----------------------------
SELECT setval('"public"."django_migrations_id_seq"', 20, true);

-- ----------------------------
-- Primary Key structure for table django_migrations
-- ----------------------------
ALTER TABLE "public"."django_migrations" ADD CONSTRAINT "django_migrations_pkey" PRIMARY KEY ("id");
